name: separaga
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  url_launcher: ^6.2.2
  flutter:
    sdk: flutter
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  fonts:
    - family: Droid Sans
      fonts:
        - asset: assets/fonts/DroidSans.ttf
        - asset: assets/fonts/DroidSans-Bold.ttf
          weight: 700
