// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5r6eCqMl9mH6jMbCGieJjNUWwubDc72E',
    appId: '1:306986669419:web:a578a69b24fe1f7842a82e',
    messagingSenderId: '306986669419',
    projectId: 'separaga-fe085',
    authDomain: 'separaga-fe085.firebaseapp.com',
    storageBucket: 'separaga-fe085.appspot.com',
    measurementId: 'G-Z8YVH66TDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQup81wf13WVA9AiyV3JhDEHHlTbW9cqg',
    appId: '1:306986669419:android:be1b4c05b8f7405742a82e',
    messagingSenderId: '306986669419',
    projectId: 'separaga-fe085',
    storageBucket: 'separaga-fe085.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm_rQD6t7PWVUNFhKM8mBaLc0xGGN5LFY',
    appId: '1:306986669419:ios:a707f27501a68e9e42a82e',
    messagingSenderId: '306986669419',
    projectId: 'separaga-fe085',
    storageBucket: 'separaga-fe085.appspot.com',
    iosBundleId: 'com.example.separaga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm_rQD6t7PWVUNFhKM8mBaLc0xGGN5LFY',
    appId: '1:306986669419:ios:c1d0b7961a9e4ead42a82e',
    messagingSenderId: '306986669419',
    projectId: 'separaga-fe085',
    storageBucket: 'separaga-fe085.appspot.com',
    iosBundleId: 'com.example.separaga.RunnerTests',
  );
}
